## 感知机算法作业 ##

用感知机算法求下列模式分类的解向量
$$w1:{(0\,0\,0)^T, (1\,0\,0)^T,(1\,0\,1)^T,(1\,1\,0)^T}$$
$$w2:{(0\,0\,1)^T, (0\,1\,1)^T,(0\,1\,0)^T,(0\,1\,1)^T}$$

In [1]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
# from mpl_toolkits.mplot3d import axes3d

In [3]:
# 输入数据
data = np.array(([0, 0, 0, 1],
                [1, 0, 0, 1],
                [1, 0, 1, 1],
                [1, 1, 0, 1],
                [0, 0, -1, 1],
                [0, -1, -1, -1],
                [0, -1, 0, -1],
                [0, -1, -1, -1]))

In [6]:
data.T
data.T.shape
b = data.T[:, 1]
c = np.array([0, 0, 0, 0])
print(np.dot(b, c))

0


In [7]:
# 定义感知机学习函数
def Perceptron(data):
    m, n = data.shape    # 返回矩阵的行数和列数
    w = np.zeros(m)     # w的维度应该和x曾广后的维度相同
    flag = 0        # 这里的flag=0表示所有分类均正确
    
    while(flag == 0):    # 只要flag！=0说明还需要迭代
        flag = 0
        for x in range(n):    # 对于每一个x的曾广,取矩阵的列向量
            if np.dot(w, data[:,x]) <= 0:
                flag += 1
                w += data[:,x]
    
    return w

In [8]:
w = Perceptron(data.T)

In [9]:
print(w)

[ 0. -1. -1.  0.]


## 多类感知机算法 ##

用多类感知机算法求下列模式的判别函数：
$$w1:(-1\,-1)^T$$
$$w2:(0\,0)^T$$
$$w3:(1\,1)^T$$

将模式增广
$$x_{1}:(-1\,-1\,1)^T$$
$$x_{2}:(0\,0\,1)^T$$
$$x_{3}:(1\,1\,1)^T$$

In [5]:
# 输入样本
import numpy as np
data = np.array([[-1, -1, 1],
               [0, 0, 1],
               [1, 1, 1]])

In [6]:
dataT = data
label = np.array([0, 1, 2])
m, n = dataT.shape    # m为输入模式的维度
label_num = 3         # 类别数目
sample_num = 3
w = np.zeros(shape=(n, label_num))    # 权重矩阵
d = np.zeros(label_num)

In [7]:
def sign(val):
    if val >= 0:
        return 1
    else:
        return 0

# 定义多类感知机算法

def MultiPerceptron(data, label):
    flagW = False    # 初始化flagW,
    while(not flagW):
        for x, c in zip(data, label):
            print("\n")
            print("x is {}".format(x))
            print("Class is {}".format(c))
            print("\n")
            for i in range(label_num):
                d[i] = np.dot(w[:,i], x)
                print("d{} is {}".format(i, d[i]))
            
            flag = 0    # 判断是否有d[i]>=d[c]
            for i in range(sample_num):
                if label[i] != c:
                    flag += sign(d[i]-d[c])
                    # print("flag is {}".format(flag))
                    w[:, i] -= (sign(d[i]-d[c]))*x
            if flag != 0:    # 一旦有d[i]>=d[c]说明d[需要被更新]
                w[:,c] += x
            else:
                flagW = True
            print("w.T is")
            print(w.T)
        
    return w

In [8]:
w = MultiPerceptron(dataT, label)



x is [-1 -1  1]
Class is 0


d0 is 0.0
d1 is 0.0
d2 is 0.0
w.T is
[[-1. -1.  1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


x is [0 0 1]
Class is 1


d0 is 1.0
d1 is -1.0
d2 is -1.0
w.T is
[[-1. -1.  0.]
 [ 1.  1.  0.]
 [ 1.  1. -2.]]


x is [1 1 1]
Class is 2


d0 is -2.0
d1 is 2.0
d2 is 0.0
w.T is
[[-1. -1.  0.]
 [ 0.  0. -1.]
 [ 2.  2. -1.]]


x is [-1 -1  1]
Class is 0


d0 is 2.0
d1 is -1.0
d2 is -5.0
w.T is
[[-1. -1.  0.]
 [ 0.  0. -1.]
 [ 2.  2. -1.]]


x is [0 0 1]
Class is 1


d0 is 0.0
d1 is -1.0
d2 is -1.0
w.T is
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 2.  2. -2.]]


x is [1 1 1]
Class is 2


d0 is -3.0
d1 is 0.0
d2 is 2.0
w.T is
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 2.  2. -2.]]


In [9]:
print(w)

[[-1.  0.  2.]
 [-1.  0.  2.]
 [-1.  0. -2.]]


In [11]:
data2 = np.array([[0, 0, 0],
                 [1, 0, 0],
                 [1, 0, 1],
                 [1, 1, 0],
                 [0, 0, 1],
                 [0, 1, 1],
                 [0, 1, 0],
                 [1, 1, 1]])
label2 = np.array([0, 0, 0, 0, 1, 1, 1, 1])
m, n = data2.shape    # m为输入模式的维度
label_num = 2         # 类别数目
sample_num = 8
w = np.zeros(shape=(n, label_num))    # 权重矩阵
d = np.zeros(label_num)

In [12]:
w = MultiPerceptron(data2, label2)



x is [0 0 0]
Class is 0


d0 is 0.0
d1 is 0.0


IndexError: index 4 is out of bounds for axis 0 with size 2